# Generated by Django 3.0.8 on 2020-08-06 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='state',
            field=models.CharField(choices=[('_undefined', '_undefined'), ('_user_is_not_confirmed', '_user_is_not_confirmed'), ('_authorized_admin', '_authorized_admin')], default='_undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_code_send_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
