# Generated by Django 3.1 on 2020-08-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_notify', '0002_auto_20200806_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='code_confirmed',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_code_send_time',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='state',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
